name: Daily Portfolio Update

on:
  schedule:
    # Run at 4:30 PM EST (after market close at 4:00 PM)
    # This is 21:30 UTC during standard time, 20:30 UTC during daylight time
    - cron: '30 21 * * 1-5'  # Monday through Friday
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-portfolio:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        
    - name: Update portfolio data
      env:
        FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
        ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
      run: |
        python backend/update_portfolio.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "📊 Daily portfolio data update - $(date +'%Y-%m-%d %H:%M')"
          git push
        fi
